# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-25 13:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighbor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, max_length=140, null=True)),
                ('avatar', smartfields.fields.ImageField(blank=True, null=True, upload_to='avatar_photos/')),
                ('hood', models.CharField(blank=True, max_length=40, null=True)),
                ('fav_animal', models.CharField(blank=True, max_length=40, null=True)),
                ('hobby', models.CharField(blank=True, max_length=40, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
    ]
