# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-25 15:49
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0003_auto_20190325_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fav_animal',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=smartfields.fields.ImageField(default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
